# Use the official Python image as the base image
FROM python:3.11.6-alpine3.17
# Install the application dependencies
# RUN npm install
# RUN pip install -r requirements.txt

# Define the entry point for the container
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]